# Generated by Django 6.0.6 on 2026-06-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='debt',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
