# Generated by Django 6.0.6 on 2026-06-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_add_description_to_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
