# Generated by Django 6.0.6 on 2026-06-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_add_title_to_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
