# Generated by Django 6.0.6 on 2026-06-29 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_add_training_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingExample',
        ),
    ]
